import '@@/styles/globals.css';
import type {Metadata} from 'next';
import {Open_Sans} from 'next/font/google';

const inter = Open_Sans({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Nextjs Discord Bot | Budapester Boonorchester [BOON]',
    description: 'Custom discord bot to manage the knowledge database and more fun commands',

    keywords: [
        'nextjs',
        'discord',
        'bot',
        'boilerplate',
        'react',
        'typescript',
        'discord bot development',
        'nextjs discord bot',
        'discord bot framework',
    ],
    authors: [
        {
            name: 'Patrick Schmidt',
            url: 'https://github.com/dev-fritte',
        },
    ],
    creator: 'Patrick Schmidt',
    publisher: 'https://github.com/dev-fritte',
    openGraph: {
        title: 'Nextjs Discord Bot | Budapester Boonorchester [BOON]',
        description: 'Custom discord bot to manage the knowledge database and more fun commands',
        url: 'https://discord-bot-boon.vercel.app/',
        type: 'website',
    },
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <head>
            <title>Next Js Discord Bot Boilerplate | Mark Matthew Vergara</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
            <meta
                name="google-site-verification"
                content="9L9yVl1B38S_ABkJE_s2iQbhCLNYOgPMi_C8kKrWFAg"
            />
        </head>
        <body className={`${inter.className}`}>{children}</body>
        </html>
    );
}
